GET http://localhost:7777

###
GET http://localhost:7777/health


###
POST http://localhost:7777/auth/login
content-type: application/json

{
  "username": "admin",
  "password": "Truthy@123",
  "remember": true
}

###
Get http://localhost:7777/auth/activate-account

###
Get http://localhost:7777/auth/profile

###
Get http://localhost:7777/auth/token-info

###
Post http://localhost:7777/restaurants
content-type: application/json

{
  "name": "faker.company.companyName()",
  "email": "faker.internet.email()",
  "description": "`restaurant ${i} description`",
  "website": "`restaurant ${i} description`",
  "avatar": "`restaurant ${i} description`",
  "city": "`restaurant ${i} description`",
  "address1": "`restaurant ${i} description`",
  "address2": "`restaurant ${i} description`",
  "address3": "`restaurant ${i} description`",
  "country": "`restaurant ${i} description`",
  "background": "`restaurant ${i} description`",
  "assentColor": "`restaurant ${i} description`",
  "totalOrders": 1,
  "totalAmountSpent": 1.1,
  "openStatus": "CLOSE",
  "favorite": "CLOSE",
  "hasDiscount":false,
  "isVerified":false
}

###
Patch http://localhost:7777/restaurants/1
content-type: application/json

{
  "name": "大盛日本料理_4",
  "email": "admin_5@truthy.com",
  "description": "restaurant 1 description",
  "website": "https://www.openrice.com/",
  "favorite": "1",
  "avatar":  "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4",
  "background":  "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4",
  "assentColor":  "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4",
  "totalOrders": 1,
  "totalAmountSpent": 1.1
}

###
Get http://localhost:7777/restaurants

###
Get http://localhost:7777/restaurants/1

###
Delete http://localhost:7777/restaurants/1

###
Get http://localhost:7777/users

###
Get http://localhost:7777/roles

###
Post http://localhost:7777/auth/register
content-type: application/json

{
  "username": "demo@devias.io1",
  "email": "demo1@devias.io",
  "name": "demo_frontend1",
  "password": "Password123!"
}

###
Post http://localhost:7777/refresh

###
Put http://localhost:7777/auth/change-password

###
Put http://localhost:7777/auth/forgot-password

###
Put http://localhost:7777/auth/profile

###
Put http://localhost:7777/auth/reset-password

###
Put http://localhost:7777/revoke/:id

###
PUT http://localhost:7777/users/1
content-type: application/json

{ "username": "admin", "address":"new address" }


###
DELETE http://localhost:7777/users/1

###
PUT http://localhost:7777/users/1
content-type: application/json

{ "username": "admin", "contact":"new contact" }

###
POST http://localhost:7777/logout
content-type: application/json

{}

###
POST http://localhost:7777/users
content-type: application/json

{ "email":"hello@123.com",   "name":"hello",
  "roleId":1, "status":"active", "username":"hello"
}

###
GET http://localhost:7777/users/1

###
GET http://localhost:7777/users

###
GET http://localhost:7777/dashboard/os

###
GET http://localhost:7777/dashboard/browser
