
###
PUT http://localhost:7777/tags/3
content-type: application/json

{ "username": "admin", "address":"new address" }

###
Get http://localhost:7777/tags


###
DELETE http://localhost:7777/tags/2

###
PATCH http://localhost:7777/tags/4
content-type: application/json

{ "username": "admin", "description":"new contact" }

###
POST http://localhost:7777/tags
content-type: application/json

{
  "username": "new tag",
  "description": "`tag ${i} description`"
}

###
GET http://localhost:7777/tags/3

###
GET http://localhost:7777/tags

###
GET http://localhost:7777/dashboard/os

###
GET http://localhost:7777/dashboard/browser

###
POST http://localhost:7777/logout
content-type: application/json

{}
