version: "3"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    shm_size: '256m'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
      POSTGRES_DB: test
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: pgadmin4@pgadmin.org
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_MASTER_PASSWORD_REQUIRED: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    ports:
      - "5050:80"

volumes:
  postgres:
  pgadmin-data:
