services:
  minio:
    image: minio/minio:latest
    command: server /data
    restart: unless-stopped
    environment:
      MINIO_BROWSER: on
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"

  cms:
    build:
      # context: .
      dockerfile: cms/Dockerfile
    volumes:
      - ./cms:/usr/src/app
    working_dir: /usr/src/app
    command: sleep infinity
    ports:
      - 3000:3000

  backend:
    build:
      # context: .
      dockerfile: backend/Dockerfile
    # user: 1000:1000
    volumes:
      - ./backend:/usr/src/app
      - backend_node_modules:/usr/src/app/node_modules
    working_dir: /usr/src/app
    ports:
      - 7777:7777
    env_file:
      - ./backend/.env
    # networks:
    #   - webnet
    depends_on:
      - postgres
    command: sleep infinity

  postgres:
    # container_name: postgres
    hostname: postgres
    image: postgres:12
    # env_file:
    #   - .env
    # networks:
    #   - webnet
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: truthy
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    # container_name: redis
    hostname: redis
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
    volumes:
      - .:/data
    # env_file:
    #   - .env
    ports:
      - 6379:6379

# networks:
#   webnet:
#     driver: bridge

volumes:
  pgdata:
  backend_node_modules:
